"""SessionBudget — execution budget enforcer for DoS / Unbounded Consumption.

Mitigates OWASP Agentic AI T4 (Resource Overload) at the session level,
complementing the sliding-window RateLimiter which operates at the
agent/tool call frequency level.

Three independent controls, all checked inside check_tool_call before
the gate runs:

  1. Step counter        — total tool invocations in this session
  2. Per-prompt fan-out  — tool calls generated by a single user prompt
  3. Loop detection      — near-duplicate (tool, args) fingerprints in a window

Every control counts something SHAI observes directly at its own boundary.

Each session is identified by (agent_id, session_id). Budgets are
per-session and are cleaned up when reset() is called (e.g. on session end).

Not a Scanner — called directly by the SHAI facade in check_tool_call.
Returns (allowed: bool, reason: str | None).
"""
from __future__ import annotations

import json
import threading
from collections import deque
from dataclasses import dataclass
from typing import Any


@dataclass
class ExecutionLimits:
    """Per-agent execution limits.  All limits default to None (disabled).

    max_steps:              total tool calls allowed per session
    max_tool_calls_per_prompt: fan-out ceiling per user turn
    loop_detection_window:  how many recent fingerprints to compare against
    loop_similarity_threshold: 0.0–1.0 — Jaccard similarity above which a
                            call is flagged as a loop duplicate
    """
    max_steps: int | None = None
    max_tool_calls_per_prompt: int | None = None
    loop_detection_window: int = 0   # 0 = disabled; set > 0 to enable
    loop_similarity_threshold: float = 0.95

    def any_enabled(self) -> bool:
        """True when any control is configured — loop detection included.

        Callers gate the whole enforcer on this, so omitting loop detection
        here made a loop-detection-only config unreachable.
        """
        return (
            self.max_steps is not None
            or self.max_tool_calls_per_prompt is not None
            or self.loop_detection_window > 0
        )


class _SessionState:
    """Mutable state for one (agent_id, session_id) pair."""

    def __init__(self) -> None:
        self.steps: int = 0
        self.prompt_calls: int = 0       # resets when prompt_id changes
        self.current_prompt_id: str | None = None
        # deque of arg fingerprints (frozensets of "key=value" strings)
        self.recent_fingerprints: deque[frozenset] = deque()


def _fingerprint(tool_name: str, args: dict[str, Any]) -> frozenset:
    """Return a frozenset of 'key=value' strings representing this call.

    Values are truncated to avoid unbounded memory on large payloads.
    """
    items: set[str] = {f"__tool__={tool_name}"}
    for k, v in args.items():
        try:
            raw = json.dumps(v, default=str)
        except Exception:
            raw = str(v)
        items.add(f"{k}={raw[:128]}")
    return frozenset(items)


def _jaccard(a: frozenset, b: frozenset) -> float:
    """Similarity of two call fingerprints.

    Two empty sets score 1.0 here, unlike the identically-named helper in
    session_accumulator, which scores 0.0. Deliberate: a fingerprint always
    carries at least `__tool__=<name>`, so empty-vs-empty means two
    argument-less calls to the same tool — a loop. In the accumulator the sets
    are text bigrams, where empty-vs-empty means nothing was said and no
    similarity should be claimed.
    """
    if not a and not b:
        return 1.0
    intersection = len(a & b)
    union = len(a | b)
    return intersection / union if union else 0.0


class SessionBudget:
    """Thread-safe session-level execution budget enforcer.

    One instance per SHAI facade, shared across all agents and sessions.
    Each session is keyed by (agent_id, session_id).
    """

    def __init__(self) -> None:
        # {(agent_id, session_id): _SessionState}
        self._sessions: dict[tuple[str, str], _SessionState] = {}
        self._lock = threading.Lock()

    # ──────────────────────────────────────────────────────────────────────
    # Public API
    # ──────────────────────────────────────────────────────────────────────

    def check(
        self,
        agent_id: str,
        session_id: str,
        tool_name: str,
        args: dict[str, Any],
        limits: ExecutionLimits,
        *,
        prompt_id: str | None = None,
    ) -> tuple[bool, str | None]:
        """Check and record a tool call attempt against the session budget.

        prompt_id: opaque string identifying the user turn that triggered this
                   call.  When prompt_id changes, the per-prompt fan-out counter
                   resets.  The SHAI facade passes TurnSignals.turn_id, so the
                   turn boundary established at scan_input drives the reset.
                   Fan-out enforcement is skipped when prompt_id is None —
                   which is the case for flows that never call scan_input.

        Returns (allowed, deny_reason).  deny_reason is None when allowed=True.
        Records the call regardless of outcome (step counter always increments
        on an allowed call — denied calls are not counted toward budget).
        """
        if not limits.any_enabled():
            return True, None

        key = (agent_id, session_id)
        with self._lock:
            if key not in self._sessions:
                self._sessions[key] = _SessionState()
            state = self._sessions[key]

            # ── Reset per-prompt counter when turn changes ─────────────────
            if prompt_id is not None and prompt_id != state.current_prompt_id:
                state.current_prompt_id = prompt_id
                state.prompt_calls = 0

            # ── 1. Step counter ────────────────────────────────────────────
            if limits.max_steps is not None and state.steps >= limits.max_steps:
                return False, (
                    f"session budget exceeded: {state.steps} steps reached "
                    f"max_steps={limits.max_steps}"
                )

            # ── 2. Per-prompt fan-out ──────────────────────────────────────
            if (
                prompt_id is not None
                and limits.max_tool_calls_per_prompt is not None
                and state.prompt_calls >= limits.max_tool_calls_per_prompt
            ):
                return False, (
                    f"session budget exceeded: prompt has already triggered "
                    f"{state.prompt_calls} tool calls "
                    f"(max_tool_calls_per_prompt={limits.max_tool_calls_per_prompt})"
                )

            # ── 3. Loop detection ──────────────────────────────────────────
            if limits.loop_detection_window > 0:
                fp = _fingerprint(tool_name, args)
                for prev in state.recent_fingerprints:
                    if _jaccard(fp, prev) >= limits.loop_similarity_threshold:
                        return False, (
                            f"loop detected: tool '{tool_name}' called with "
                            f"near-identical arguments within the last "
                            f"{limits.loop_detection_window} invocations "
                            f"(similarity≥{limits.loop_similarity_threshold})"
                        )

            # ── Record the allowed call ────────────────────────────────────
            state.steps += 1
            if prompt_id is not None:
                state.prompt_calls += 1

            # Update rolling fingerprint window
            if limits.loop_detection_window > 0:
                fp = _fingerprint(tool_name, args)
                state.recent_fingerprints.append(fp)
                while len(state.recent_fingerprints) > limits.loop_detection_window:
                    state.recent_fingerprints.popleft()

            return True, None

    def reset(self, agent_id: str, session_id: str | None = None) -> None:
        """Clear budget state for a session or all sessions of an agent.

        Call on session end or agent deregistration.
        """
        with self._lock:
            if session_id is not None:
                self._sessions.pop((agent_id, session_id), None)
            else:
                keys = [k for k in self._sessions if k[0] == agent_id]
                for k in keys:
                    del self._sessions[k]

    def snapshot(self, agent_id: str, session_id: str) -> dict:
        """Return a read-only snapshot of current budget state.  Used in tests."""
        key = (agent_id, session_id)
        with self._lock:
            state = self._sessions.get(key)
            if state is None:
                return {"steps": 0, "prompt_calls": 0}
            return {
                "steps":        state.steps,
                "prompt_calls": state.prompt_calls,
            }
