"""SessionBudget — execution budget enforcer for DoS / Unbounded Consumption.

Mitigates OWASP Agentic AI T4 (Resource Overload) at the session level,
complementing the sliding-window RateLimiter which operates at the
agent/tool call frequency level.

Three independent controls, all checked inside check_tool_call before
the gate runs:

  1. Step counter        — total tool invocations in this session
  2. Per-prompt fan-out  — tool calls generated by a single user prompt
  3. Loop detection      — near-duplicate (tool, args) fingerprints in a window

Every control counts something SHAI observes directly at its own boundary.

Each session is identified by (agent_id, session_id). Budgets are
per-session and are cleaned up when reset() is called (e.g. on session end).

Persistence
-----------
Backed by a state-store adapter (see adapters/state_store/base.py) via its
`.kv` facet, rather than a hardcoded in-process dict — same storage model as
the crescendo accumulator. The recommended default backend is `memory`: this
sits on the tool-call gate's pre-checks, so a networked backend here adds
latency to every tool call in a deployment with no multi-replica need.

A store failure (adapter raises) follows `on_error`: `fail_closed` (default)
denies the call; `fail_open` allows it without recording budget state for it.

Not a Scanner — called directly by the SHAI facade in check_tool_call.
Returns (allowed: bool, reason: str | None).
"""
from __future__ import annotations

import asyncio
import json
import logging
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from harness.core.types import OnError

if TYPE_CHECKING:
    from harness.adapters.state_store.base import StateStore

log = logging.getLogger(__name__)


@dataclass
class ExecutionLimits:
    """Per-agent execution limits.  All limits default to None (disabled).

    max_steps:              total tool calls allowed per session
    max_tool_calls_per_prompt: fan-out ceiling per user turn
    loop_detection_window:  how many recent fingerprints to compare against
    loop_similarity_threshold: 0.0–1.0 — Jaccard similarity above which a
                            call is flagged as a loop duplicate
    """
    max_steps: int | None = None
    max_tool_calls_per_prompt: int | None = None
    loop_detection_window: int = 0   # 0 = disabled; set > 0 to enable
    loop_similarity_threshold: float = 0.95

    def any_enabled(self) -> bool:
        """True when any control is configured — loop detection included.

        Callers gate the whole enforcer on this, so omitting loop detection
        here made a loop-detection-only config unreachable.
        """
        return (
            self.max_steps is not None
            or self.max_tool_calls_per_prompt is not None
            or self.loop_detection_window > 0
        )


def _fingerprint(tool_name: str, args: dict[str, Any]) -> list[str]:
    """Return a sorted list of 'key=value' strings representing this call.

    A sorted list rather than a frozenset because the fingerprint is
    persisted as JSON — the store never sees a frozenset. `_jaccard` below
    reconstructs a frozenset for the actual comparison.

    Values are truncated to avoid unbounded memory on large payloads.
    """
    items: set[str] = {f"__tool__={tool_name}"}
    for k, v in args.items():
        try:
            raw = json.dumps(v, default=str)
        except Exception:
            raw = str(v)
        items.add(f"{k}={raw[:128]}")
    return sorted(items)


def _jaccard(a: list[str], b: list[str]) -> float:
    """Similarity of two call fingerprints.

    Two empty sets score 1.0 here, unlike the identically-named helper in
    session_accumulator, which scores 0.0. Deliberate: a fingerprint always
    carries at least `__tool__=<name>`, so empty-vs-empty means two
    argument-less calls to the same tool — a loop. In the accumulator the sets
    are text bigrams, where empty-vs-empty means nothing was said and no
    similarity should be claimed.
    """
    fa, fb = frozenset(a), frozenset(b)
    if not fa and not fb:
        return 1.0
    intersection = len(fa & fb)
    union = len(fa | fb)
    return intersection / union if union else 0.0


def _new_state() -> dict[str, Any]:
    """A session's starting state. A fresh value each time: `recent_fingerprints`
    is mutated in place, so a shared template would carry one session's calls
    into every session that starts after it."""
    return {
        "steps": 0,
        "prompt_calls": 0,
        "current_prompt_id": None,
        "recent_fingerprints": [],
    }


class SessionBudget:
    """State-store-backed session-level execution budget enforcer.

    One instance per SHAI facade, shared across all agents and sessions.
    Each session is keyed by (agent_id, session_id).
    """

    def __init__(self, store: StateStore, *, on_error: OnError = OnError.FAIL_CLOSED) -> None:
        """`store` bundles `.kv` (KVStore) — see adapters/state_store/base.py.
        Constructed and injected by the caller (core/wiring.py).
        """
        self._store = store   # kept for close() and test introspection
        self._kv = store.kv
        self._on_error = on_error
        # Per-session asyncio locks — serialise concurrent calls on the same
        # session without blocking unrelated sessions on the same store.
        self._locks: dict[str, asyncio.Lock] = {}
        self._locks_lock = asyncio.Lock()

    async def _lock_for(self, key: str) -> asyncio.Lock:
        async with self._locks_lock:
            if key not in self._locks:
                self._locks[key] = asyncio.Lock()
            return self._locks[key]

    # ──────────────────────────────────────────────────────────────────────
    # Public API
    # ──────────────────────────────────────────────────────────────────────

    async def check(
        self,
        agent_id: str,
        session_id: str,
        tool_name: str,
        args: dict[str, Any],
        limits: ExecutionLimits,
        *,
        prompt_id: str | None = None,
    ) -> tuple[bool, str | None]:
        """Check and record a tool call attempt against the session budget.

        prompt_id: opaque string identifying the user turn that triggered this
                   call.  When prompt_id changes, the per-prompt fan-out counter
                   resets.  The SHAI facade passes TurnSignals.turn_id, so the
                   turn boundary established at scan_input drives the reset.
                   Fan-out enforcement is skipped when prompt_id is None —
                   which is the case for flows that never call scan_input.

        Returns (allowed, deny_reason).  deny_reason is None when allowed=True.
        Records the call regardless of outcome (step counter always increments
        on an allowed call — denied calls are not counted toward budget).

        A store failure follows `on_error` — see class docstring.
        """
        if not limits.any_enabled():
            return True, None

        key = f"{agent_id}:{session_id}"
        lock = await self._lock_for(key)
        async with lock:
            try:
                return await self._check_locked(key, tool_name, args, limits, prompt_id)
            except Exception:
                log.error(
                    "session budget store unreachable — %s",
                    self._on_error,
                    exc_info=True,
                    extra={"agent_id": agent_id, "session_id": session_id},
                )
                if self._on_error == OnError.FAIL_OPEN:
                    return True, None
                return False, "session budget store unreachable — denying (fail_closed)"

    async def _check_locked(
        self,
        key: str,
        tool_name: str,
        args: dict[str, Any],
        limits: ExecutionLimits,
        prompt_id: str | None,
    ) -> tuple[bool, str | None]:
        raw = await self._kv.get(key)
        state = json.loads(raw) if raw is not None else _new_state()

        # ── Reset per-prompt counter when turn changes ─────────────────
        if prompt_id is not None and prompt_id != state["current_prompt_id"]:
            state["current_prompt_id"] = prompt_id
            state["prompt_calls"] = 0

        # ── 1. Step counter ────────────────────────────────────────────
        # Deny branches below are read-only: a denied call is not counted
        # toward budget, so nothing is written back to the store for it —
        # only the reset of the per-prompt counter above (if any) persists,
        # picked up on the next allowed call for this session.
        if limits.max_steps is not None and state["steps"] >= limits.max_steps:
            return False, (
                f"session budget exceeded: {state['steps']} steps reached "
                f"max_steps={limits.max_steps}"
            )

        # ── 2. Per-prompt fan-out ──────────────────────────────────────
        if (
            prompt_id is not None
            and limits.max_tool_calls_per_prompt is not None
            and state["prompt_calls"] >= limits.max_tool_calls_per_prompt
        ):
            return False, (
                f"session budget exceeded: prompt has already triggered "
                f"{state['prompt_calls']} tool calls "
                f"(max_tool_calls_per_prompt={limits.max_tool_calls_per_prompt})"
            )

        # ── 3. Loop detection ──────────────────────────────────────────
        fp = _fingerprint(tool_name, args) if limits.loop_detection_window > 0 else None
        if fp is not None:
            for prev in state["recent_fingerprints"]:
                if _jaccard(fp, prev) >= limits.loop_similarity_threshold:
                    return False, (
                        f"loop detected: tool '{tool_name}' called with "
                        f"near-identical arguments within the last "
                        f"{limits.loop_detection_window} invocations "
                        f"(similarity≥{limits.loop_similarity_threshold})"
                    )

        # ── Record the allowed call ────────────────────────────────────
        state["steps"] += 1
        if prompt_id is not None:
            state["prompt_calls"] += 1

        if fp is not None:
            state["recent_fingerprints"].append(fp)
            while len(state["recent_fingerprints"]) > limits.loop_detection_window:
                state["recent_fingerprints"].pop(0)

        await self._kv.put(key, json.dumps(state).encode())
        return True, None

    async def reset(self, agent_id: str, session_id: str | None = None) -> None:
        """Clear budget state for a session or all sessions of an agent.

        Call on session end or agent deregistration. Takes each session's
        lock, so a reset cannot land in the middle of a check's
        read-modify-write and be overwritten by it.
        """
        if session_id is not None:
            keys = [f"{agent_id}:{session_id}"]
        else:
            keys = await self._kv.list(f"{agent_id}:")
        for key in keys:
            async with await self._lock_for(key):
                await self._kv.delete(key)

    async def snapshot(self, agent_id: str, session_id: str) -> dict:
        """Return a read-only snapshot of current budget state.  Used in tests."""
        raw = await self._kv.get(f"{agent_id}:{session_id}")
        if raw is None:
            return {"steps": 0, "prompt_calls": 0}
        state = json.loads(raw)
        return {"steps": state["steps"], "prompt_calls": state["prompt_calls"]}

    async def close(self) -> None:
        """Close the underlying store. Idempotent — called from SHAI.close()."""
        await self._store.close()
